### ISSUE TITLE
using ally.js modules instead of the distributable

### ISSUE THREAD

**Issue by rodneyrehm** [LevelFourAB/mara#1]
Thanks for giving ally.js a shot <3

Did you know that you can load [ES6 modules](http://allyjs.io/getting-started.html#Using-ES6-modules)? since you're currently only using `ally.query.firstTabbable` and `ally.maintain.hidden`, loading only those modules should mean less weight…

**Comment by aholstenson** [comment]
Thank you, that's a really good suggestion. We've been using ally.js in a larger project (and love it) where this code was extracted from, I'll make sure to update with the use of the modules.

**Comment by aholstenson** [comment]
Finally got around to refactoring and using the smaller imports these last few weeks. Closing this issue.
